[build]
  command = "corepack disable && npm run build"
  publish = ".output/public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20.18.0"
  SECRETS_SCAN_ENABLED = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"
  SHARP_IGNORE_GLOBAL_LIBVIPS = "1"
  COREPACK_ENABLE_STRICT = "0"
  COREPACK_ENABLE_AUTO_PIN = "false"
  COREPACK_ROOT = "/dev/null"
